serve: main.go
	go get github.com/swaggo/swag/cmd/swag
	swag init
	go run main.go
db:
	docker run -d --rm -e MONGO_INITDB_ROOT_USERNAME=mongoadmin -e MONGO_INITDB_ROOT_PASSWORD=secret -p 27017:27017 mongo
reset:
	find . ! -name *.json ! -name *.yml ! -name *.yaml -delete